### ISSUE TITLE
Update documentation in https://docs.openkm.com/kcenter/view/okm-6.3-com/active-directory-example-with-login-based-on-filtering-users-by-roles.html

### ISSUE THREAD

**Issue by DrydenK** [openkm/document-management-system#101]
Hi, 

I would like to request a documentation page for OpenKM to be updated. In https://docs.openkm.com/kcenter/view/okm-6.3-com/active-directory-example-with-login-based-on-filtering-users-by-roles.html, at the beginning of the sample for OpenKM.xml, there are three entries pointing to a version 3.1:
<?xml version="1.0" encoding="UTF-8"?>
<beans:beans xmlns:beans="http://www.springframework.org/schema/beans"
             xmlns:security="http://www.springframework.org/schema/security"
             xmlns:task="http://www.springframework.org/schema/task"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://www.springframework.org/schema/beans
                                 http://www.springframework.org/schema/beans/spring-beans-3.1.xsd
                                 http://www.springframework.org/schema/security
                                 http://www.springframework.org/schema/security/spring-security-3.1.xsd
                                 http://www.springframework.org/schema/task
                                 http://www.springframework.org/schema/task/spring-task-3.1.xsd">

These cause tomcat to fail in a restart, indicating that it should be 3.2. Could you please update that information, or remove completely the version information, as suggested by " jllort" in https://forum.openkm.com/viewtopic.php?f=4&t=22016?

Thank you,

Roberto Greiner

**Comment by darkman97i** [comment]
I have changed the documentation. Do you have the stack trace error when in the xml you set 3.1 rather 3.2 ? because I would like to document it in the troubleshooting section
https://docs.openkm.com/kcenter/view/okm-6.3-com/ldap-troubleshooting.html

**Comment by darkman97i** [comment]
At the end I found it and I have documented.
