### ISSUE TITLE
OpenKM-6.3.6.zip  Why this one is Professional Extension

### ISSUE THREAD

**Issue by YPKSEU139** [openkm/document-management-system#150]
<img width="764" alt="_20181030163751" src="https://user-images.githubusercontent.com/7539369/47705727-5ec9f680-dc62-11e8-96d6-b6a70088b9d5.png">

我按照这个下载的 war包进行部署，为何安装完成的OpenKM为   Professional Extension  ？？？

<img width="249" alt="_20181030164017" src="https://user-images.githubusercontent.com/7539369/47705771-8325d300-dc62-11e8-8bcb-4a6c2036349a.png">

**Comment by YPKSEU139** [comment]
I am deploying according to this downloaded war package. Why is OpenKM installed as a professional extension?

**Comment by darkman97i** [comment]
It is a bug, by mistake we copyed from professional edition wrong data.

**Comment by YPKSEU139** [comment]
> 这是一个错误，错误地从专业版错误的代码复制。

OK ，Thank you for your reply，I love OpenKM

**Comment by gnujavasergio** [comment]
@darkman97i corrected issue

![seleccion_163](https://user-images.githubusercontent.com/654790/47766237-192e1d80-dca4-11e8-93bd-fd698ac4548f.png)

@YPKSEU139 thanks Thanks for reporting the bug
