### ISSUE TITLE
Mobile version raise an error in search view

### ISSUE THREAD

**Issue by a0930xxx11** [openkm/document-management-system#159]
Currently under testing 6.3.4 and 6.3.6 version, Use openkm search function same filename 『test』 in mobile devices show error loading page.

Openkm.log is shown as

"GET /OpenKM/mobile/Search?action=searchNormal&content=&filename=test&keywords= HTTP/1.1" 500 991

But the 6.3.4 version can search the file normal, Will the two versions differ on mobile devices?

6.3.4 version successful search filename
![28989](https://user-images.githubusercontent.com/34538008/48338235-179b2700-e6a0-11e8-9186-6283d4e48a95.jpg)

6.3.6 version search filename fail
![default](https://user-images.githubusercontent.com/34538008/48338268-2a156080-e6a0-11e8-8295-73dd309d165f.jpg)

**Comment by darkman97i** [comment]
It is a bug, in the ResultSet object has been changed in the latest version.
