### ISSUE TITLE
CSV Exporter doesn't work

### ISSUE THREAD

**Issue by frank4569** [openkm/document-management-system#167]
I'm trying to use the "Search results" export to .csv file button. It's not working. 
I'm using the Community Edition 6.3.7 running on the distributed virtual machine. Can you help me?

I posted the same on the forum
https://forum.openkm.com/viewtopic.php?f=5&t=22243

**Comment by darkman97i** [comment]
Possible problem with JSON and decode the URL ( similar issue with professional version )

**Comment by frank4569** [comment]
Seems to me that the generated JSON request is empty:

GENERAL
Request URL: http://192.168.10.16:8080/OpenKM/frontend/CSVExporter?action=find&lang=en-GB&json={%22author%22:%22%22,%20%22keywords%22:%22%22,%20%22content%22:%22%22,%20%22name%22:%22%22,%20%22path%22:%22%2Fokm%3Aroot%22,%20%22mimeType%22:%22%22,%20%22domain%22:1,%20%22mailFrom%22:%22%22,%20%22mailTo%22:%22%22,%20%22mailSubject%22:%22%22,%20%22categoryUuid%22:%22%22,%20%22categoryPath%22:%22%22,%20%22operator%22:%22and%22}&compact=false
Request Method: GET
Status Code: 400 
Remote Address: 192.168.10.16:8080
Referrer Policy: no-referrer-when-downgrade


QUERY
action: find
lang: en-GB
json: {"author":"", "keywords":"", "content":"", "name":"", "path":"/okm:root", "mimeType":"", "domain":1, "mailFrom":"", "mailTo":"", "mailSubject":"", "categoryUuid":"", "categoryPath":"", "operator":"and"}
compact: false

**Comment by gnujavasergio** [comment]
@frank4569 
Error solved the pull request was done
The CSV file can now be generated correctly

**Comment by frank4569** [comment]
Thank you for solving it!
How can I update my OpenKM?
