### ISSUE TITLE
Error 404 in com.openkm.sdk4csharp.impl.DocumentImpl.createDocumentSimple

### ISSUE THREAD

**Issue by ricardoamm** [openkm/document-management-system#168]
Hi, I using OpenKM Comunity Version 6.3.7. 
I need to manage a folder trough WebServices, but I'm facing an error when creating Documents.
The OKMRest.dll version is 1.2.1. 

I the previous version (6.3.6) I was able to create Documents, but unable to get Content. In the current version I can get Content but I can't create.

What I'm doing wrong?

Regards

**Comment by pherrera87** [comment]
Hello,

The OpenKM version and the sdk for .net are correct, please send me a screenshot of the error.
I share the following code:

`using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using com.openkm.sdk4csharp;
using com.openkm.sdk4csharp.bean;
using System.IO;

namespace OKMRest
{
    public class Program
    {
        static void Main(string[] args)
        {
            String host = "http://localhost:8080/OpenKM";
            String username = "user1";
            String password = "pass1";
            OKMWebservice ws = OKMWebservicesFactory.newInstance(host, username, password);

            try
            {
                FileStream fileStream = new FileStream("E:\\logo.png", FileMode.Open);
                ws.createDocumentSimple("/okm:root/logo.png", fileStream);
                fileStream.Dispose();
            } catch (Exception e) {
                System.Console.WriteLine(e.ToString());
            } 
        }
    }
}`

**Comment by ricardoamm** [comment]
![error](https://user-images.githubusercontent.com/26299584/53766583-20bc3800-3ecb-11e9-9ea9-306cb2af8f5d.png)

**Comment by ricardoamm** [comment]
Hello,

I made web debug, and I think there is a problem with the sdk. The createDocumentSimple URL seems wrong. Is "/OpenKMservices/rest/document/createSimple" and should be "/OpenKM/services/rest/document/createSimple"

![image](https://user-images.githubusercontent.com/26299584/53793369-a5d43b00-3f25-11e9-9f9f-5603b660a181.png)

The sdk source code is available to download?

Regards

**Comment by pherrera87** [comment]
Hello, 

Something is not right with the URL, try inserting "/" at the end, for example:
String host = "http://localhost:8080/OpenKM/";

**Comment by ricardoamm** [comment]
Hello,

In the other methods, I don't have problems. 
I follow your sugestion and it seems ok.
Thanks

Regards
