### ISSUE TITLE
Document browse - column names not inline with columns

### ISSUE THREAD

**Issue by rpintaric** [openkm/document-management-system#17]
There is a small  issue/bug in the css which does not correctly align column names vs. content in the file browser. I did some research and find out that styles.css dont have declared padding-left: 2px in .gwt-ScrollTable .dataTable tr td.

Before padding
![image](https://user-images.githubusercontent.com/30823944/29059994-3bca50f4-7c18-11e7-9455-55790147612b.png)

After insertion
![image](https://user-images.githubusercontent.com/30823944/29060042-6c2609fa-7c18-11e7-873a-203416d68728.png)

**Comment by darkman97i** [comment]
Seems you have added metadata columns, without these columns and hidding the others, the table is right ?

**Comment by rpintaric** [comment]
Actually i dont thin so, but its harder to notice the diference. If u remove all metadata columns, and inspect element like okm-DisableSelect u cant see that the size of element is 2px smaller then the header element. The diference is that column names have padding by 2px, and the columns dont. 2 by 2 and with the extra 4 columns u get 22px space and outlined columns.

I printscreened with extra metadata columns do that u can notice the space...

**Comment by darkman97i** [comment]
I have verified and seems is as you explain. I have applied the patch in the source code and asked for merge request. Next week will be applied and you will get it from 6.3-DEV branch.
