### ISSUE TITLE
java.lang.NullPointerException when bulk uploading documents

### ISSUE THREAD

**Issue by kefren69** [openkm/document-management-system#170]
Problem with Data_browser in administrator import tool:

All tests done and the issue description are at the link below

[Here](https://forum.openkm.com/viewtopic.php?f=5&t=22248)

Regards and thanks

Giancarlo

**Comment by kefren69** [comment]
as I understand this is a bug and will be address in version 6.3.8
Question when is version 6.3.8 coming out?
Basically this little issues blocks the implementation of the system in a francophone environment.
:-)

**Comment by monzer24** [comment]
Hello,
I don't know if this bug has been fixed or not yet, but I have the same issue.
I want to upload a file to OpenKM with a custom UI client but it always returns NullPointerException.
I am using OpenKM 6.3.9

**Comment by darkman97i** [comment]
This issue has not any kind of relation with "custom UI client". It talks about "administrator import tool", what seems is not your case.
