### ISSUE TITLE
Document can be download when disable download on user profile

### ISSUE THREAD

**Issue by teddyloy** [openkm/document-management-system#171]
OKM version:6.3.7 and below 6.3.7;
Description:
1, disable download privilege on user profile for user A
2, login as this user A
3, navigate to the file which user A has read privilege (w/o write)
4, select one document and mouse on the file
5, user A can download the file use keyboard "Ctrl + D" on Chrome/firefox or other browser.

It was critical issue!!!

**Comment by darkman97i** [comment]
@gnujavasergio take a look at Keyboard.java and into ExtendedDockPanel.java where is used KEY_D constant
