### ISSUE TITLE
Frontend Folder is missing inside webapp

### ISSUE THREAD

**Issue by ansarmnnit** [openkm/document-management-system#176]
After "login.jsp" am redirected to "frontend/index.jsp"  file  but it is missing, gives me 404 error. even in source code there is no frontend folder inside webapps.

**Comment by darkman97i** [comment]
Are you trying to compile the source code? what is your scenario?

**Comment by ansarmnnit** [comment]
Step1:-Checkout From Github(Successful)
Step2:-Source code is complied Successfully with no errors
Step3:-Launch Login Page (http://localhost:8080/OpenKM/login.jsp)
Step4:-After Successful Authentication ,i'am redirected to this page (http://localhost:8080/OpenKM/frontend/index.jsp) :-1:
 Now This page is Not Available (404 not found). i even crossed checked your jsp folder it is also not there.

**Comment by darkman97i** [comment]
Are you executing the command line:
```
mvn clean package -Dmaven.test.skip
```
You should watch permutations compilations:
```
[INFO]    Compiling 5 permutations
[INFO]       Compiling permutation 0...
[INFO]       Process output
[INFO]          Compiling
[INFO]             Compiling permutation 3...
[INFO]       Process output
[INFO]          Compiling
[INFO]             Compiling permutation 2...
[INFO]       Process output
[INFO]          Compiling
[INFO]             Compiling permutation 1...

```

After compilation into target do you have a folder OpenKM/frontend? should be there a file named index.jsp

I have compiled the master branch and for me worked.

**Comment by ansarmnnit** [comment]
its not working when am trying to run project on server inside eclipse(for development purpose), in case of maven build yes it is creating "frontend/index.jsp" am aware of that.

**Comment by darkman97i** [comment]
Seems the problem is the way you are starting the project from eclipse. I do not suggest use eclipse deploy, I suggest you copy war file or create an alias into webapps from target/OpenKM to webapps/OpenKM

**Comment by ansarmnnit** [comment]
I want to add some functionality on top of openkm community version for internal usage,if i can't get the project working on eclipse, how would i develop that functionality as it would be difficult to debug issues.

**Comment by darkman97i** [comment]
I'm sure the virtual machine and eclipse into work right. I continue thinking is the way how you are deploying war file from eclipse, you should not use eclipse deploy will not works.

![Add and Remove  _113](https://user-images.githubusercontent.com/958703/55557769-de189600-56ea-11e9-9dc6-a82fa6ba82df.png)

**Comment by ansarmnnit** [comment]
ok i'will download the image file (OpenKM-ComPorDev.ova ) and try  using the eclipse IDE which is provided by you,and will let you know it worked for me or not.

**Comment by darkman97i** [comment]
Did the community OVA solved your issue?

**Comment by ansarmnnit** [comment]
yes it does but every time i have to make build from terminal  (mvn clean package -Dmaven.test.skip)
then have to deploy it on server to test feature added by me.

**Comment by darkman97i** [comment]
If you are making changes in the user interface you can use super dev mode https://docs.openkm.com/kcenter/view/okm-6.3-com/eclipse-tips.html#DebugGWTfrontenduserinterfacewithGWTSuperDevMode

**Comment by darkman97i** [comment]
Ticket closed due to inactivity.
