### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by thiagodds** [openkm/document-management-system#18]
[This REST API](https://www.openkm.com/wiki/index.php/RESTful_Guide) works?

I need upload documents with javascript, I think that I can use the REST API to do this. 
The link above is deprecated and I can't find the new version.

**Comment by darkman97i** [comment]
The new documentation section about Documentation (https://docs.openkm.com/kcenter/view/okm-6.3-com/restful.html).
Also I suggest check this project (https://github.com/darkman97i/kamify) what it have some javascript request to REST API and can suggest you some ideas. For example look here (https://github.com/darkman97i/kamify/blob/master/js/download.js).

Tell me if this solved the question and I will close the issue.

**Comment by thiagodds** [comment]
@darkman97i are there plans to implement token authentication? 
Basic authentication isn't a good choice today.

**Comment by darkman97i** [comment]
If you want to help us on it, you are welcome. I think might be is not much complicated with spring security. The best scenario should be get running with Basic and JWT together ( here there's some sample ahow how get running basic and digest, I think might be is possible get running basic with JWT http://www.baeldung.com/basic-and-digest-authentication-for-a-rest-api-with-spring-security )

**Comment by thiagodds** [comment]
Thank you.
