### ISSUE TITLE
Permissions issue

### ISSUE THREAD

**Issue by Logicbloke** [openkm/document-management-system#182]
Hello there,

I'm running the latest version having just upgraded from 6.3.6 to 6.3.8 thinking it would hopefully solve my issue but it didn't. Here's the issue: I have a folder that I created under /okm:personal and when I create a new user and give it the ROLE_USER role, I get a bunch of errors about missing folders and paths starting from /okm:trash.

`com.openkm.core.RepositoryException: PathNotFoundException: 76062562-689d-444c-9218-3b20f103d7ca : /okm:trash`

This issue doesn't seem to happen when I assign the ROLE_ADMIN role to the newly created user before switching him back to ROLE_USER but alas the read only permission don't work on /okm:personal/MYFOLDER despite adding them in the security tab from my other admin account (not okmAdmin which I deleted).

Adding the read only permissions on the okm:personal folder or the one that I created underneath doesn't work for either my user or the role and the users assigned to it.

Any ideas what's going on?
Thank you very much,

**Comment by darkman97i** [comment]
All the userss should be member of ROLE_USER or ROLE_ADMIN ( the super user ). In your case your case I think you have forget to set ROLE_USER and that is the reason why is not able to accesing /okm:trash, another possible mistake is that you have removed ROLE_USER from okm:trash, you should not remove from there.

**Comment by Logicbloke** [comment]
Even with ROLE_USER assigned to the user I'm still getting the issue about okm:trash, but what about that other folder under okm:personal that I'm not seeing?

All I see is the folder that the regular user owns under okm:personal but not the other custom folder I created and have given read permissions for the ROLE_USER role?

I can make a video for you to demo this if needed.
Thanks,

**Comment by darkman97i** [comment]
did you changed the security in the okm:trash, make an screenshot where we can watch okm:trash and the security assigned.

**Comment by Logicbloke** [comment]
I made a couple of screencasts with both issues.

Folder inaccessible despite having the proper permissions:
https://streamable.com/egcol

okm:trash/Username not found:
https://streamable.com/ute40

Please advise,
Thank you.

**Comment by darkman97i** [comment]
I attach some screenshots about how security should be set in the main nodes ( okm:personal, okm:mail and okm:trash ).

All the users should be members of ROLE_USER always ( except members of ROLE_ADMIN, this is a mandatory rule used by OpenKM to identify standard or administrator users).

https://ibb.co/s23kMWY

https://ibb.co/kh40Jz4

**Comment by Logicbloke** [comment]
Thank you for your response, 

There's absolutely no way to update security for okm:trash eventhough I'm connected as a user that has the role ROLE_ADMIN.
![image](https://user-images.githubusercontent.com/502521/57175395-75385100-6e43-11e9-898a-e1a6468c3de0.png)


> All the users should be members of ROLE_USER always ( except members of ROLE_ADMIN, this is a mandatory rule used by OpenKM to identify standard or administrator users).

If you had watched the video, you'd see that it is exactly what we're doing.

2. The other issue about the folder that's under okm:personal is also intriguing. Have you watched the video? What's your input on it? It looks like a bug to me.

Please note that we no longer have okmAdmin in the system but rather another user with the ROLE_ADMIN role. I hope it's not hardcoded in the files.

Please advise,
Thanks!

**Comment by darkman97i** [comment]
I do not know how have you changed the security ( only I can suppose you have done something from API ). Go to Administration > Scripting and execute:

`com.openkm.api.Auth.getInstance().grantRole(null,"/okm:trash","ROLE_USER",16,false);`

Apply the same for the other nodes

**Comment by Logicbloke** [comment]
Hello,

Thanks for this,

For some reason it's giving me the following error:
`bsh.EvalError: Sourced file: inline evaluation of: ``com.openkm.api.Auth.getInstance().grantRole(null,"/okm:trash","ROLE_USER",16,fal . . . '' : Class or variable not found: com.openkm.api.Auth : at Line: 1 : in file: inline evaluation of: ``com.openkm.api.Auth.getInstance().grantRole(null,"/okm:trash","ROLE_USER",16,fal . . . '' : com .openkm .api .Auth .getInstance ( )`

Not sure where it's coming from.

**Comment by Logicbloke** [comment]
I'm creating a separate issue for the 2nd suspected bug.

**Comment by darkman97i** [comment]
com.openkm.api.Auth does not exist, the right name is OKMAuth

**Comment by Logicbloke** [comment]
That didn't work either but I got it to work by looking up the UUID of the folder directly and adding it to the permissions table.

Thanks!
