### ISSUE TITLE
Openkm6.3.6 can't open the login page after running for a while

### ISSUE THREAD

**Issue by thageru** [openkm/document-management-system#183]
Hey, I have two questions to ask.
my openkm version is 6.3.6
Q1：The log stops, jstack finds that it is blocked on the LanguageDAO.findAll() method, and has been waiting for the connection. There is no query in the query database connection. The connection status is sleep. The following picture is a partial jstackscreenshot
![1](https://user-images.githubusercontent.com/26118711/56635368-e5064900-6697-11e9-946c-ea6ee45eaa4e.png)

Q2：When I use shutdown.sh to close openkm, sometimes all processes under the user are killed. The server version is redhat-6.4.

**Comment by darkman97i** [comment]
I suspect the issue is with your database, might be is not right configured because the error seems happens when it is trying to get connection. Check your jdbc url.

In adition, althouhgt will not be the issue, I suggest you connect to the database and check the table be created and there're rows into OKM_TRANSLATION table.

**Comment by thageru** [comment]
> I suspect the issue is with your database, might be is not right configured because the error seems happens when it is trying to get connection. Check your jdbc url.
> 
> In adition, althouhgt will not be the issue, I suggest you connect to the database and check the table be created and there're rows into OKM_TRANSLATION table.

It should not be that I suddenly appeared after running for a while, and it happened every once in a while, it seems that it depends on my frequency of use.
I am using mysql5.7

**Comment by darkman97i** [comment]
If you want record a video, for better understanding, but are you looking for a OpenKM issue and this does not seems an OpenKM issue, seems a configuration issue. Check your jdbc url https://docs.openkm.com/kcenter/view/okm-6.3-com/configuring-mysql-and-mariadb.html and ensure your database is alive and is not killing the poll. At the end I suggest check a fresh installation with fresh database configuration.

**Comment by thageru** [comment]
Emmm, if I am going to migrate the database from MySQL to HSQLDB, is there any good way?

**Comment by darkman97i** [comment]
Has not sense for a production environment.
