### ISSUE TITLE
where is initing sql

### ISSUE THREAD

**Issue by TOBACCOCN** [openkm/document-management-system#186]
I could not find the initing sql, we do not need it?  maybe I have no other problem, but I get error Table 'openkm.okm_node_base' doesn't exist and so on.

**Comment by darkman97i** [comment]
Check if into the database you have tables I suspect the whole database will be clean. Is this a fresh installation?

**Comment by TOBACCOCN** [comment]
I got the reason, when tomcat startup, it would auto create tables in database by setting hibernate.hbm2ddl = create in OpenKM.cfg, but in source code, there is no OpenKM.cfg. I found this file in dir generated after installing of openkm-6.3.2-community-windows-installer.exe.
