### ISSUE TITLE
docker container startup error

### ISSUE THREAD

**Issue by seregaxvm** [openkm/document-management-system#187]
Not sure if this it the right place to report this, but there's a problem with docker image [openkm/openkm-ce:6.3.7](https://hub.docker.com/r/openkm/openkm-ce). 
When staring container with the command `docker run --rm --name test --detach -p 8080:8080 openkm/openkm-ce:6.3.7` I get error 404. Running `openkm/openkm-ce:6.3.6` with the same command works just fine.
Here's the log file: [okm.log](https://github.com/openkm/document-management-system/files/3152579/okm.log).

**Comment by monkiki** [comment]
Just tested and works fine. I don't know why gives you an error on your computer.

**Comment by seregaxvm** [comment]
This is weird. It runs on my other machine too.

**Comment by monkiki** [comment]
Yes, it's quite odd. It should work everywhere. Maybe your docker installation is damaged. I don't know.
