### ISSUE TITLE
Read-only permissions on okm:personal custom subfolder

### ISSUE THREAD

**Issue by Logicbloke** [openkm/document-management-system#188]
Hey guys,

Can anyone please look into this?
https://streamable.com/egcol

It seems like we can't have our `Group` account access a custom folder we created under okm:personal and to which we have given not only the read-only access through ROLE_USER but also through the username itself.

The folder just wouldn't show up when we connect using the user's account.

Any ideas?
Thanks a lot!

**Comment by darkman97i** [comment]
Two things:
1- personal folder should only get accessed by the owner, except super user who have access to everything ( has not been thought this space for sharing with other users, has been thought as a private area )
2- the okm:personal, okm:mail and okm:trash, should have ROLE_USER read access ( only ) do not remove it, that allows to standard users ( not administrators ) accessing to their own child node.

**Comment by Logicbloke** [comment]
PRODUCTION is a custom folder that we created and tried to have other users access it with read-only. Are you saying we made a mistake by putting it under okm:personal? Then what's an alternative parent folder we can use to have something shared among users?

Thank you very much.

**Comment by darkman97i** [comment]
You should use taxonomy with the right security for this kind of purpose. Tell me if I can close the ticket?

**Comment by Logicbloke** [comment]
I'll look into taxonomy then. Thanks!
