### ISSUE TITLE
 Mail notification all user  

### ISSUE THREAD

**Issue by zengsentry** [openkm/document-management-system#190]
Whether OpenKM support config notification all user use the configuration mail account , need not change the from field ?

**Comment by darkman97i** [comment]
OpenKM uses only the email account configured in server.xml for sending notifications. User email accounts are only for reading purposes.

Read this section in the documentation https://docs.openkm.com/kcenter/view/okm-6.3-com/configuring-tomcat-mail.html

**Comment by zengsentry** [comment]
> OpenKM uses only the email account configured in server.xml for sending notifications. User email accounts are only for reading purposes.
> 
> Read this section in the documentation https://docs.openkm.com/kcenter/view/okm-6.3-com/configuring-tomcat-mail.html

Thank you for you replay,

I  know OpenKM uses only the email account configured in server.xml for sending notifications.
However  if the  sub user mail account  is not the same as the mail  configured in server.xml , 
OpenKM will throw an exception  when send mail.
 `EBUG SMTP: MessagingException while sending, THROW: 
com.sun.mail.smtp.SMTPSendFailedException: 550 5.7.1 Client does not have permissions to send as this sender`

The reason is my mail server unsupported  change from field.

**Comment by darkman97i** [comment]
Take a look if you have a parameter named "send.mail.from.user" in Administration > Configuration parameters ( in case you have it, you should disable ).
