### ISSUE TITLE
Repeated Workflow instance with run config

### ISSUE THREAD

**Issue by xiaoke9273** [openkm/document-management-system#191]
we came accross a very strange issue during we developed a file workflow. We developed a file workflow with run_config and loaded it in openkm. The openkm created two repeated workflow instance with same created time when we executed the workflow. But we developed other file workflow without run_config,the openkm created a wokflow instance normally. 
we debugged the source code for this problem,we found the program will run the following code when the workflow with run_config,
```java
	public void runProcessDefinition() {
		if (drawed) {
			if (manager.getValidationProcessor().validate()) {
				runProcessDefinitionWithValues();
			} else {
				workflowWidgetToFire.hasPendingProcessDefinitionForms();
			}
		} else {
			getProcessDefinitionForms(name);
		}
	}
```
the condition, manager.getValidationProcessor().validate(),will return true, so it will call runProcessDefinitionWithValues() which create a workflow instance, but manager.getValidationProcessor().validate() as following:
```java
public boolean validate(List<String> uuids, String... names) {
		this.uuids = uuids;
		result = true;
		pluginsValidated = 0;
		result = result && super.validate(names);
		// Always evaluate plugins rpc calls at ends
		if (plugins > 0 && validatorToFire != null) {
			waitUntilValidatorsFinished();
		} else if (plugins == 0 && validatorToFire != null) {
			validatorToFire.validationWithPluginsFinished(result);
		}
		return result;
	}
```
it will call the validatorToFire.validationWithPluginsFinished(result), this funciton also includes a runProcessDefinitionWithValues() as following:
```java
	public void validationWithPluginsFinished(boolean result) {
		if (result) {
			runProcessDefinitionWithValues();
		} else {
			workflowWidgetToFire.hasPendingProcessDefinitionForms();
		}
	}
```
it will again call runProcessDefinitionWithValues() which will create second workflow instance.
I did not understand function of manager.getValidationProcessor().validate(), so why it need call runProcessDefinitionWithValues() again. May it is a bug or my configuration issue?

**Comment by darkman97i** [comment]
Please try the branch issue/191 ( https://github.com/openkm/document-management-system/tree/issue/184 ).

Test with a workflow what with run_config and without run_config ( both scenarios ).

**Comment by darkman97i** [comment]
I have reproduced the issue, check the branch issue/191
https://github.com/openkm/document-management-system/tree/issue/191
