### ISSUE TITLE
undeletable folder

### ISSUE THREAD

**Issue by palo654** [openkm/document-management-system#192]
hello
we discovered an issue in OpenKM.
Using the SDK there is possinle to create folders, that are not valid for OpenKM.
For example folder named ' " '
the folder is shown in the gui, but not possible to create on filesystem.
the result is, that if you click on the folder the GUI raises an error.

The question is, how to delete these folders?

thank you

**Comment by darkman97i** [comment]
Get the UUID from the parent folder and execute the query:
```sql
SELECT * FROM OKM_NODE_BASE WHERE NBS_PARENT='parent uuid';
```
Update the name
```sql
UPDATE NBS_NAME FROM OKM_NODE_BASE WHERE NBS_UUID='uuid of the problematic node'
```

What SDK version did you used?
What method in the SDK? there are two methods for it.

**Comment by palo654** [comment]
thank you. it worked.

good question which version it is. how do I check this?

**Comment by darkman97i** [comment]
Go to administration panel and there should be shown the version
