### ISSUE TITLE
Checksum failure in node 

### ISSUE THREAD

**Issue by jahirzener** [openkm/document-management-system#199]
When i start a Repository checker (any Folders), I receive the message "Checksum failure for node
![Capture](https://user-images.githubusercontent.com/55479273/65123762-054af180-da05-11e9-90f0-894de318a962.JPG)

**Comment by jahirzener** [comment]
nothing exported. after installation Ver-6.3.8, we have added manually few documents through Add document. to make sure everything works good we have checked the repository checker.

**Comment by darkman97i** [comment]
Add please an additional screenshot with the options marked in the repository checker.

**Comment by jahirzener** [comment]
![rep](https://user-images.githubusercontent.com/55479273/65147043-528f8900-da2e-11e9-9779-33ed0eb439bc.JPG)

**Comment by jahirzener** [comment]
![rep](https://user-images.githubusercontent.com/55479273/65147110-7783fc00-da2e-11e9-91b6-aa60e70a4f4a.JPG)
