### ISSUE TITLE
Add createMissingFolders

### ISSUE THREAD

**Issue by MLDMoritz** [openkm/document-management-system#213]
Hey,

when trying to upload a document with e.g. a date (`/okm:root/2020/01/30`) it would be needed to recursively call createFolder. It would be simpler to add the `createMissingFolders` method to the rest api.

**Comment by MLDMoritz** [comment]
I recreated the functionality on my client side. This works, just is slower than directly via the api:

```php
    final public function createMissingFolders(string $path): void
    {
        $checkPath = '';

        foreach (explode('/', substr($path, 1)) as $elto) {
            $checkPath = $checkPath.'/'.$elto;

            if (!$this->hasNode($checkPath)) {
                $this->createFolder($checkPath);
            }
        }
    }
```

**Comment by darkman97i** [comment]
The method exists in the OpenKM API but is not exposed across the web services. We will work in extending the current SDK.
