### ISSUE TITLE
rest api: setPropertiesSimple JSON

### ISSUE THREAD

**Issue by MLDMoritz** [openkm/document-management-system#214]
Hey,

`PUT` to `services/rest/propertyGroup/setPropertiesSimple` with Content-Type `application/json` doesn't work. It accepts the request with Status `204` but doesn't update the property values.

Calling the same method with `application/xml` and xml body works fine.

**Comment by darkman97i** [comment]
@gnujavasergio Maybe the bug is in the OpenKM API or maybe in the SDK ( but I suspect it is in the OpenKM side ) -> talk with me before starting

**Comment by gnujavasergio** [comment]
Hello @darkman97i works well with json

Lo probe con esto
`
The metadata group definition used in the samples:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE property-groups PUBLIC "-//OpenKM//DTD Property Groups 2.0//EN"
                                 "http://www.openkm.com/dtd/property-groups-2.0.dtd">
<property-groups>
  <property-group label="Technology" name="okg:technology">
    <select label="Type" name="okp:technology.type" type="multiple">
      <option label="Alfa" value="t1"/>
      <option label="Beta" value="t2" />
      <option label="Omega" value="t3" />
    </select>
    <select label="Language" name="okp:technology.language" type="simple">
      <option label="Java" value="java"/>
      <option label="Python" value="python"/>
      <option label="PHP" value="php" />
    </select>
    <input label="Comment" name="okp:technology.comment"/>
    <textarea label="Description" name="okp:technology.description"/>
    <input label="Link" type="link" name="okp:technology.link"/>
  </property-group>
</property-groups>
`
Add a metadata group with json
`
curl -u okmAdmin:admin -H "Accept: application/json" \
  -X PUT -H "Content-Type: application/json" \
  -d '{"simplePropertyGroup": [{"name": "okp:technology.type","value": "t1"}, {"name": "okp:technology.comment","value": "RESTful rulez!"}]}' \
  http://localhost:8080/OpenKM/services/rest/propertyGroup/setPropertiesSimple?nodeId=f435f687-d0f8-4366-a37d-65fb37d03e1d\&grpName=okg:technology
  `
This example I removed from the documentation https://docs.openkm.com/kcenter/view/okm-6.3-com/restful.html

**Comment by darkman97i** [comment]
Hi MLDMoritz  please try with the sample @gnujavasergio shared
