### ISSUE TITLE
NB: JAVA_HOME should point to a JDK not a JRE

### ISSUE THREAD

**Issue by Amrouane** [openkm/document-management-system#215]
I followed steps of installation for windows shown in this [YOUTUBE VIDEO](https://www.youtube.com/watch?v=7C40UMajJ0k). But when it finishes dowloading and extracting files i get this error:

```
- Configure service
The JAVA_HOME environment variable is not defined correctly
This environment variable is needed to run this program
NB: JAVA_HOME should point to a JDK not a JRE
```

![image](https://user-images.githubusercontent.com/26816971/73554879-d03bba80-444c-11ea-8709-f462a5ef9934.png)

And I am pretty sure my JAVA_HOME variable is set to the path: `C:\Program Files\Java\jdk-13.0.2`
and `C:\Program Files\Java\jdk-13.0.2\bin ` is also added to path

**Comment by darkman97i** [comment]
Must have installed jdk 1.8 with upper version OpenKM will not working.
Ensure you have JAVA_HOME in your environment variables ( check the beggining of this documentation section https://docs.openkm.com/kcenter/view/okm-6.3-com/installing-on-windows.html )

**Comment by Amrouane** [comment]
@darkman97i  Thanks. it worked with this jdk version, the installation completed but the service won't start. It gives me this:
`Windows could not start the OpenKM Service on local computer . for more information review the system event log .If this is a Non -Microsoft service ,contact the service vendor`

**Comment by Amrouane** [comment]
@darkman97i 
installation could not install the service correctly. Any thoughts:
![image](https://user-images.githubusercontent.com/26816971/73646574-07db7a00-467a-11ea-83de-52a989a6fbe3.png)

**Comment by darkman97i** [comment]
Must execute the installer as Administrator user ( because you need Administrator right for registering the service )

**Comment by Amrouane** [comment]
@darkman97i As you can see in the screen, I am running the installer as administrator

**Comment by darkman97i** [comment]
Check if you have previous service named OpenKM, can not be registered twice.

In tomcatXXXX/bin/ you have service.bat ( https://docs.openkm.com/kcenter/view/okm-6.3-com/installing-on-windows.html#ConfiguringTomcatasaservice )
