### ISSUE TITLE
Issue with extencion

### ISSUE THREAD

**Issue by killmasta93** [openkm/document-management-system#220]
Hi,
I was wondering if someone could shed some light im trying to enable the live mode to edit the files on 6.3.9 but when i go to Administration > Utilities > Database query i do not find database query

any ideas?

Thank you

**Comment by darkman97i** [comment]
I attached an screenshot
![Selección_001](https://user-images.githubusercontent.com/958703/85926300-d4a2bd00-b89e-11ea-8116-d1235c91eb91.png)
