### ISSUE TITLE
Purge Folder API in .net SDK

### ISSUE THREAD

**Issue by dharm0826** [openkm/document-management-system#227]
The Purge Folder function is not available in .net SDK. Please see this feature can be added as it proves to be one of the crucial features in Recycle Bin(Trash).

**Comment by darkman97i** [comment]
@gnujavasergio if not exist the method in the REST API, create it. Then forward to @pherrera87

**Comment by gnujavasergio** [comment]
Hello  @dharm0826 the method purgeFolder this created in this pull request https://github.com/openkm/document-management-system/pull/224

**Comment by gnujavasergio** [comment]
@pherrera87 the purgeFolder method has to be created in the sdk4net and this is the method in the code.
