### ISSUE TITLE
Extend PropertyGroupService API

### ISSUE THREAD

**Issue by dharm0826** [openkm/document-management-system#228]
Hi

In propertygroup section, application level add/set propertygroup exposed API is also required in order to provide node level metadata feature.

**Comment by darkman97i** [comment]
In the PropertyGroupService class are exposed the metadata methods from REST, in the OKMPropertyGroup class it is the OpenKM core API. What do you missing ?

**Comment by dharm0826** [comment]
In further detail, sdk4net exposes all propertygroup(metadata) REST methods for node(document) related operations only. There is no such method available for adding new propertygroup to avail it for setting it to the nodes(document).

**Comment by darkman97i** [comment]
You are talking about "registering a new XML property group definition" in the application. Is that?

**Comment by dharm0826** [comment]
Yes, in OpenKM Admin UI, there is a metadata screen from where propertygroup.xml file can get updated(by adding or removing propertygroup).

**Comment by darkman97i** [comment]
@gnujavasergio Add method to update property group xml and probably will not be only registering also edit ( in community edition it is done in two steps, change xml definition and then registering )
