### ISSUE TITLE
Advanced search folder shows only trash

### ISSUE THREAD

**Issue by tbclark3** [openkm/document-management-system#235]
When I first initialized my installation, the advanced search worked correctly.  However, after deleting at least one personal document, it doesn't.  When I select "My Documents" as the context, then try to select a folder in the Advanced tab, the only folders I see are under the okm:trash root.  I cannot select any of my personal folders. I have played around with it for several hours and cannot change it.

**Comment by darkman97i** [comment]
What version did you have installed?
I suggest go to Administration > Tools > Rebuild indexes and choose the option lucene indexes ( the process may take some minutes to be completed -> it depends on your repository size, hardware performance ).

**Comment by tbclark3** [comment]
Thanks for your response!  Rebuilding the index didn't make any difference.  I am using version 6.3.9 which is the latest in Docker.  I had changed security parameters to read_recursive and am_more, but changed them back and it didn't make a difference.  As an additional test, I spun up a second unrelated docker instance, and advanced search did the same thing.

**Comment by darkman97i** [comment]
Please share an screenshot for understanding the results and the type of the search you are doing.

**Comment by tbclark3** [comment]
I am logged in as myself, tclark. I am an administrator.  

![Screenshot from 2020-05-26 12-26-07](https://user-images.githubusercontent.com/4080951/82942544-f7168300-9f4c-11ea-8855-fa30ea2788de.png)

**Comment by darkman97i** [comment]
Let me show and screenshot of the basic tab

**Comment by tbclark3** [comment]
Sorry, not sure which screen you would like to see.

**Comment by darkman97i** [comment]
![82942544-f7168300-9f4c-11ea-8855-fa30ea2788de](https://user-images.githubusercontent.com/958703/83229101-b0f93380-a187-11ea-92fd-f847b0716483.png)

**Comment by tbclark3** [comment]
![Screenshot from 2020-05-29 06-08-09](https://user-images.githubusercontent.com/4080951/83263410-68d01600-a173-11ea-98d9-46b680227561.png)

**Comment by darkman97i** [comment]
@gnujavasergio Possible bug. When context is my documents it seems only allow filtering by folders in the trash. Check it.

**Comment by gnujavasergio** [comment]
@darkman97i realize the review. There is an error
