### ISSUE TITLE
openkm sends wrong Content-Length header for email attachments

### ISSUE THREAD

**Issue by tbclark3** [openkm/document-management-system#238]
The attached eml file is correctly parsed after uploading to openkm.  In the Preview window I can read the body of the email and see that there are two attachments.  I can successfully download the entire email.  However, clicking on either attachment in the preview window results in download failure because openkm is sending an incorrect file size in the Content-Length header. This happens every time, and on every type of attachment.  For the attached example:

Attachment: flower1.jpeg
Actual length: 21846
Header Content-Length provided by server: 29936

Attachment: flower2.jpg
Actual length: 19566
Header Content-Length provided by server: 26812
[flowermail.eml.zip](https://github.com/openkm/document-management-system/files/4707728/flowermail.eml.zip)

**Comment by darkman97i** [comment]
@gnujavasergio Please confirm the issue in your development environment

**Comment by gnujavasergio** [comment]
Hello @darkman97i .
I resolved issue. I already assigned the merge
