### ISSUE TITLE
Disable PDF Download

### ISSUE THREAD

**Issue by phgeraldes** [openkm/document-management-system#242]
Hi there, is there any chance to block all pdf downloads from dashboard and from previewer, i follow this guide https://www.openkm.com/wiki/index.php/Downloading_restricted_buttons , and on dashboard does not download, but on preview the button is there, can someone help here using other previewer, or something else.
Thanks

**Comment by darkman97i** [comment]
Take a look here https://forum.openkm.com/viewtopic.php?f=4&t=22002&p=50156&hilit=disable#p50156 and https://forum.openkm.com/viewtopic.php?f=4&t=23437&p=50155&hilit=disable#p50155
