### ISSUE TITLE
Multiple Automation actions not running

### ISSUE THREAD

**Issue by jcardila** [openkm/document-management-system#253]
I have 3 different AddPropertyGroupToWizard actions that should each ask for metadata group fields when a document is added, but strangely only 2 of those ask for the information, the other metadata group is added to the document but with empty fields. Tried changing the Order field but I cant get it to work. Video of the issue: https://drive.google.com/file/d/12H5JXjyP5EJnbFwqsoQ3J5E-8wW-T3jH/view?usp=drivesdk
Forum post: https://forum.openkm.com/viewtopic.php?t=23595
Version 6.3.9

**Comment by jcardila** [comment]
Additional info: Deleting the automations and using instead the wizard requiring the 3 metadata groups the result is the same, the wizard only asks for information of 2 metadata groups and it adds the third one empty.

**Comment by darkman97i** [comment]
@gnujavasergio Esto me gustaría que lo probases en tu máquina local y me dices cosas al respecto. Primero quiero saber si realmente falla.
