### ISSUE TITLE
 how to encrypt documents

### ISSUE THREAD

**Issue by zohramchiri** [openkm/document-management-system#259]
hello
i have a java code of a document encryption and i want to introduce it in the source code of openKm community
my problem is how can i introduce it because i can't find the file responsable of saving document in openkm
can you please help me about the file wich contain the saving method of documents in openkm?

thank u

**Comment by darkman97i** [comment]
Correct me if I'm wrong. Basically you have a document in OpenKM and you want to crypt. Here must do several things:
1- checkout ( mark document for edition )
2- checkin ( update )
3- compact the history of versions ( because previous document versions are not crypted )
4- mark document as crypted

You want to do everything in a single method?

**Comment by zohramchiri** [comment]
I would like to add function Encrypting and decrypting the  document
In source code of openkm

Le jeudi 29 octobre 2020, Josep Llort Tella <notifications@github.com> a
écrit :

**Comment by zohramchiri** [comment]
Yes

**Comment by darkman97i** [comment]
Let's begin with something easiest, tell me what do you thing about my propose:
1- Create a class named CryptUtils ( or similar name ) in src/com/openkm/utils with two methods for crypt and decrypt, the methods should use at least a inputStream var and any aditional parameter you need.

2- Clone the project in github , add the class an ask for a pull request. 

3- Share some sample about how it works. From our side we will try to add the feature in the user interface.

**Comment by zohramchiri** [comment]
How Apple the class..
And where to add this feature to the code

Le vendredi 30 octobre 2020, Josep Llort Tella <notifications@github.com> a
écrit :

**Comment by darkman97i** [comment]
If you share a basic sample ( zip project ) we can take a look and we will suggest the best place to integrate with OpenKM.

**Comment by darkman97i** [comment]
Only for your information we have moved all the Java encryption features to a windows client what have less issues than application based in Java web starter technology ( I ignore is that was the idea you had in your mind ? )

We passed a lot of time we will close this issue.
