### ISSUE TITLE
import the document

### ISSUE THREAD

**Issue by belle561** [openkm/document-management-system#266]
what class contains the method which imports the documents under the reprosotry folders

**Comment by darkman97i** [comment]
I suggest take a look at:
* https://github.com/openkm/document-management-system/blob/master/src/main/java/com/openkm/util/impexp/RepositoryImporter.java
* https://github.com/openkm/document-management-system/blob/master/src/main/java/com/openkm/servlet/admin/RepositoryServlet.java

Do you need something else or I proceed closing the issue.

**Comment by belle561** [comment]
we have encrypted files in datastore,
in which class you have to modify to decrypt the files to be used in openkm (if you perceived, search ....)

**Comment by darkman97i** [comment]
Please do not merge distinct topics in the same issue. Open a new one if you have a different question.

Do you need something else about import documents or can proceed to close the issue?
