### ISSUE TITLE
openkm installation problem

### ISSUE THREAD

**Issue by belle561** [openkm/document-management-system#268]
good evening everyone

i installed openkm on eclipse but it found this error.
how to fix this error?

![image](https://user-images.githubusercontent.com/74243336/99729864-d40ffa80-2abb-11eb-9883-6c779ced3db0.png)

**Comment by darkman97i** [comment]
The main errors are the missing artifacts. Try to build the application from the command line:
mvn -Dmaven.test.skip=true clean package

**Comment by belle561** [comment]
how to do it,in invite cammand

**Comment by darkman97i** [comment]
First update to the latest version because the currently download code is from version 6.2.6. Follow the steps:
* right button to watch contextual menu
* choose team
* choose pull option

Then in the tool bar you should be a build configuration to build the project
![Selección_021](https://user-images.githubusercontent.com/958703/100351773-474dcb00-2fec-11eb-9040-c4c92655f8fb.png)

**Comment by zohramchiri** [comment]
can i give me the link of the latest version?

**Comment by zohramchiri** [comment]
hello,
How to solve the problem?

![image](https://user-images.githubusercontent.com/46874810/100582695-ea9f2880-32e9-11eb-89d0-1570b81eda1b.png)

**Comment by darkman97i** [comment]
What jdk version are you using to start tomcat ... I think might be the problem.
Did you downloaded the portable development environment from https://www.openkm.com/en/download.html ?

**Comment by zohramchiri** [comment]
i use jdk 1.8

**Comment by darkman97i** [comment]
You have strange things, I just downloaded the OpenKM personal development environment and I compiled and started the tomcat without any kind of issue.
As is explained in this section of our webpage https://www.openkm.com/en/download.html you might download from https://download.openkm.com/ and install like is shown in the next video
https://www.youtube.com/watch?v=9ugBYf5ggu8&feature=emb_logo

I compiled
![OpenKM-ComPorDev  Corriendo  - Oracle VM VirtualBox_037](https://user-images.githubusercontent.com/958703/100924196-9611ce00-34e0-11eb-9ea6-a327f636d018.png)


And started the tomcat what comes with OpenKM 6.3.10
![OpenKM-ComPorDev  Corriendo  - Oracle VM VirtualBox_038](https://user-images.githubusercontent.com/958703/100924310-bd689b00-34e0-11eb-94d0-a1e3a14a1aad.png)

I suggest following the steps described in our website

**Comment by soubhi** [comment]
Hi darkman97i ,
I was trying to install OpenKM using the source code by running "mvn clean package"
But I got some warnings during the compilation and exceptions during the tests . Apparently the tests failed and I got "Build failure".


So I ran with skipping the tests using  "mvn -Dmaven.test.skip=true clean package". And the build was successful.
![image](https://user-images.githubusercontent.com/34866006/106450920-d9ba9100-64ab-11eb-8d4e-27fa34fb6dd9.png)

So I checked localhost:8080/OpenKM, but it says "localhost refused to connect". 
![image](https://user-images.githubusercontent.com/34866006/106450958-e63ee980-64ab-11eb-8162-75e0d36fec2f.png)

Please help.

Also I tried installing on eclipse without tests, the build was successful, but I cannot see any "servers" tab or tomcat server like how you had in the above screenshot.
![image](https://user-images.githubusercontent.com/34866006/106451428-94e32a00-64ac-11eb-9802-fe0f8f867508.png)

PS : My internet is working fine

**Comment by darkman97i** [comment]
Seems you have not started tomcat server?

**Comment by soubhi** [comment]
Should I install Tomcat server separately?

**Comment by darkman97i** [comment]
Should start tomcat configured in eclipse ( server tab )
