### ISSUE TITLE
Slowness of the application at times

### ISSUE THREAD

**Issue by wykouadio** [openkm/document-management-system#286]
I installed OpenKM version 6.3.10 on Debian 10. I noticed an unusual slowness.
After deactivating the antivirus, importing files is easier. However, at times the application seems to be blocked for all users. And after a while, as if by magic, everything is suddenly released and the application resumes its normal operation. Where did I go wrong with the configuration?

**Comment by darkman97i** [comment]
Probably the lock is caused by Lucene search engine what should be configured in async mode.

**Comment by wykouadio** [comment]
Thank you for your answer. How to implement this option, I remember that I use OpenKM CE v6.3.10

**Comment by wykouadio** [comment]
Please, how to implement this option? I remember that I use OpenKM CE v6.3.10.

**Comment by darkman97i** [comment]
In the class com.openkm.dao.HibernateUtil should be added the parameter:
```
cfg.setProperty("hibernate.search.worker.execution", Config.HIBERNATE_SEARCH_WORKER_EXECUTION);
```

Two possible values allowed:
* sync
* async

Take a look at Config.java class to implement Config.HIBERNATE_SEARCH_WORKER_EXECUTION -> Should be load in a similar manner as is download `public static final String PROPERTY_REPOSITORY_HOME = "repository.home";`

**Comment by wykouadio** [comment]
Thank you for your valuable contribution but to tell the truth, I really don't find myself. I can't open the com.openkm.dao.HibernateUtil file to add any modification. Not being an expert in Java, can you tell me more explicitly how to do it?

**Comment by wykouadio** [comment]
Thank you for your valuable contribution but to tell the truth, I really don't find myself. I can't open the com.openkm.dao.HibernateUtil file to add any modification. Not being an expert in Java, can you tell me more explicitly how to do it?

**Comment by darkman97i** [comment]
If you do not have Java skill then can forge doing any kind of change in the application. I will forward the issue to OpenKM IT staff and when have  free time we'll do it.

**Comment by wykouadio** [comment]
Thank you very much for your assistance.
