### ISSUE TITLE
Cannot preview document with Thai Filename

### ISSUE THREAD

**Issue by teeraw-22** [openkm/document-management-system#291]
We have document that have Thai Filename that was not problem on import and add metadata group.
But when I tried preview this file, there is error PathNotFoundException. 

Application error
Class: com.openkm.core.PathNotFoundException
Message: /okm:root/Invoice/2021/???.txt
Date: Fri Jun 25 18:09:28 ICT 2021

This file is stored in /okm:root/Invoice/2021/ไทย.txt
This problem was occurred on Text file only. No problem for PDF, MSOffice documents.

Note: OpenKM v6.3.10 Community Edition.
![Error_File_Thainame](https://user-images.githubusercontent.com/86512062/123505584-2e90bb00-d68a-11eb-8c88-9957fc02cae3.jpg)

Sample file attached as below:

[ไทย.zip](https://github.com/openkm/document-management-system/files/6719729/default.zip)

**Comment by darkman97i** [comment]
I have tested in my development computer and works without problems.

![Selección_005](https://user-images.githubusercontent.com/958703/123628638-9d4d5000-d813-11eb-9536-f3e5ef33266d.png)


What browser are you using?
What OS is installed OpenKM? -> I think should not be the problem
What is your database?

**Comment by teeraw-22** [comment]
> 
> 
> I have tested in my development computer and works without problems.
> 
> ![Selección_005](https://user-images.githubusercontent.com/958703/123628638-9d4d5000-d813-11eb-9536-f3e5ef33266d.png)
> 
> What browser are you using?
> What OS is installed OpenKM? -> I think should not be the problem
> What is your database?

ํDo you can preview this file? (I also can go to properties tab as your screenshot.)

Browser : Chrome
OS: RedHat 7.5
Database: MariaDB

**Comment by teeraw-22** [comment]
Did you can simulate issue?

**Comment by darkman97i** [comment]
I can not reproduce the issue from my side.

* Check with firefox
* Can you check with a fresh browser without any kind of extensions installed. Also, If you have some antivirus, ad killer or similar I suggest disable temporary.

**Comment by teeraw-22** [comment]
- Firefox also found this issue. 
 - I already have tried on clean browser in my fresh Windows installed in VMware but still not help.

If you need more debug log, you can request to me.

Can you send me some screen recording for simulate case in your laptop?

**Comment by darkman97i** [comment]
@gnujavasergio I success to reproduce the issue. Added screenshot with possible cause.

![Selección_011](https://user-images.githubusercontent.com/958703/124148465-f5908600-da8f-11eb-9afa-a84553b909f8.png)

**Comment by teeraw-22** [comment]
How about fix of encoding problem?

**Comment by darkman97i** [comment]
My previous answers was for @gnujavasergio. He will apply changes in code.

**Comment by teeraw-22** [comment]
> My previous answers was for @gnujavasergio. He will apply changes in code.

Thank you
