### ISSUE TITLE
Problems with special characters (at least ampersands) in filenames

### ISSUE THREAD

**Issue by jaschalukasgugat** [openkm/document-management-system#298]
Hi,
ampersands in filenames are stored by their html-representation &amp; in the database (test&test.txt => test&amp;test.txt). Downloading gives the filename as is in the database (test&amp;test.txt) which is also the necessary filename for the uploaded file when editing. Both operations should use the original filname (test&test.txt).

This behaviour might also apply to other characters in the filenames.

OpenKM Forum post :
https://forum.openkm.com/viewtopic.php?p=52633#p52633

**Comment by darkman97i** [comment]
@gnujavasergio When downloading the real database name should be replaced by expected name.
