### ISSUE TITLE
Remove noreply@openkm.com from crontab task

### ISSUE THREAD

**Issue by darkman97i** [openkm/document-management-system#30]
Actual task and new crontab task, must always set the maill address as empty String. Consider first time creating crontab task when starting application.
Also must create small script for next OpenKM upgrade process in order replace all noreply@openkm.com from all existing crontab task to empty string.

**Comment by gnujavasergio** [comment]
Script  next OpenKM Upgrade

[ReplaceMail.bsh.zip](https://github.com/openkm/document-management-system/files/1395300/ReplaceMail.bsh.zip)
