### ISSUE TITLE
Search Arabic content not working in OpenKM mobile

### ISSUE THREAD

**Issue by Abu-mazi** [openkm/document-management-system#310]
I am using openkm 6.3.11 
and I'm getting  error when I do content search in Arabic from mobile : 
 parseExeotion  :cannot pars '??????':'*' or '?' not allowed as first character in Wildcard Query 
as explained in this  demonstration :

https://forum.openkm.com/viewtopic.php?t=24375
attachments

**Comment by darkman97i** [comment]
@gnujavasergio Possible problem with parameters that require encoding.

**Comment by gnujavasergio** [comment]
Hello @Abu-mazi 

Looking for a solution to your problem, a very simple solution was found that will only be a configuration.
Currently this parameter in the configuration:
tomcat.connector.uri.encoding = ISO-8859-1
![Selección_595](https://user-images.githubusercontent.com/654790/141304469-878c2a11-9ab6-4c40-b742-17ab10ef33ce.png)

For it to work you have to change to
tomcat.connector.uri.encoding = UTF-8
![Selección_596](https://user-images.githubusercontent.com/654790/141304557-56e38bab-749a-45d7-81ac-f9a0efcdaa33.png)

and with that change it will work correctly. 
Result:
![arabic](https://user-images.githubusercontent.com/654790/141304647-43a1c5a2-f0e7-473e-84df-7fae0ca0aff4.jpg)

**Comment by Abu-mazi** [comment]
Hello @gnujavasergio
This is to confirm the provided solution is working fine
Thanks
