### ISSUE TITLE
ERROR: Unknown Linux distro: unknown

### ISSUE THREAD

**Issue by nzbtuxnews** [openkm/document-management-system#313]
Trying to install OKM using OKMInstaller on a new Rocky Linux VPS, I get:

`ERROR: Unknown Linux distro: unknown`

It looks like the JAVA installer fails to detect the distro and its version.  Rocky Linux is a replacement distro for Centos.  Centos is going out in less than 2 months, so I believe OKM should support Rocky Linux out of the box.

**The shell output**

```
Running on Linux: 0.9.19-CE (build: ef7e83a)
Linux distro: unknown (Unknown - 0)
Local host: localhost (xxx.xxx.xxx.xxx)
Java version: 1.8.0_312
Free disk size: 5.5 GB
RAM size: 3.8 GB
CPU cores: 2
Server IP: xxx.xxx.xxx.xxx
Supported databases: [h2, hsqldb, mariadb, mysql, oracle, postgresql, sqlserver]
Current directory: /home/sshuser
Database [h2]: mariadb
Database host [localhost]: **********
Database name [okmdb]: **********
Database user [openkm]: **********
Database password **********
---------------------------
- Database: mariadb
- Database host: **********
- Database name: **********
- Database user: **********
- Database password: ******************
- OpenKM version: 6.3.11
- Tomcat version: 8.5.34
---------------------------
Start install process? [y/N]: y

- Downloading Tomcat: 8.5.34
....*.... 10% ....*.... 20% ....*.... 30% ....*.... 40% ....*.... 50% ....*.... 60% ....*.... 70% ....*.... 80% ....*.... 90% ....*.... 100%
- Unzipping archive. Done!
- Fix permissions... Done!
- Downloading OpenKM: 6.3.11
....*.... 10% ....*.... 20% ....*.... 30% ....*.... 40% ....*.... 50% ....*.... 60% ....*.... 70% ....*.... 80% ....*.... 90% ....*.... 100%
- Unzipping archive. Done!
- Check archive integrity... Done!
- Copy OpenKM
- Configure OpenKM
- Configure service
ERROR: Unknown Linux distro: unknown
```

**Host info**
`
- Static hostname: localhost
- Icon name: computer-vm
- Chassis: vm
- Machine ID: ********************************
- Boot ID: ********************************
- Virtualization: kvm
- Operating System: Rocky Linux 8.4 (Green Obsidian)
- CPE OS Name: cpe:/o:rocky:rocky:8.4:GA
- Kernel: Linux 4.18.0-305.19.1.el8_4.x86_64
- Architecture: x86-64

`
**Java version**
`
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)
`

An identical ticket was opened in 2019 (#86) but was closed without providing a solution, and clearly this issue remains in 2021...  Also the forum is currently down (at least from my end I get tons of PHP errors).

**Comment by darkman97i** [comment]
Wizard do not support your linux distro to configure packages, service etc... by default. We encourage using Ubuntu, Debian, Centos, Redhat, Oracle Linux where the wizard will working as expected. Otherwise should follow the description in this section of the documentation about how to installing manually https://docs.openkm.com/kcenter/view/okm-6.3-com/installing-on-ubuntu-and-debian.html

Sorry but is not possible for us know all the distro in Linux and adapt the wizard for them. I will close the issue,
