### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by fuzhiyou-69** [openkm/document-management-system#315]
Do you want to configure the full-text retrieval of openkm6.3? Can't you search the contents of word documents?
![image](https://user-images.githubusercontent.com/57322717/145192982-ee31e6b4-b112-4a6d-b28e-1669ea26c893.png)

**Comment by darkman97i** [comment]
You can search by content word documents and other types like PDF of XLS, ODT, DOC, DOCX,  among others. It depends on which text extractors do you have enabled in the application

**Comment by fuzhiyou-69** [comment]
> 您可以按内容搜索word文档和其他类型，如XLS，ODT，DOC，DOCX等的PDF。这取决于您在应用程序中启用了哪些文本提取程序

**Comment by fuzhiyou-69** [comment]
Where is the text extraction program installed? Or is it installed as a plug-in?

**Comment by darkman97i** [comment]
The text extraction process is controlled by cron job. The cron job goes across the documents pending to extract the content and depending on document type it is used a class to extract the contents. These classes are plugins that you can extend if required.
Take a look here https://github.com/openkm/document-management-system/tree/master/src/main/java/com/openkm/extractor

**Comment by fuzhiyou-69** [comment]
6.3. Version 11 does not implement full-text search, does it

**Comment by fuzhiyou-69** [comment]
6.3. 11. Does it not realize the full-text retrieval function？

**Comment by darkman97i** [comment]
Full text search in works in OpenKM and also in your language. You may have two problems:
* document is not indexed? may check in Administration stats if you have something pending in the text extraction queue and from Administration > Tools > Check text extraction of the document you are not getting results from search view.
* read about ik-analizer here https://docs.openkm.com/kcenter/view/okm-6.3-com/configuring-lucene-analyzer.html

**Comment by darkman97i** [comment]
Because not received answering from long time, I will close the issue.
