### ISSUE TITLE
Exception 'com.openkm.core.LockException' is never thrown in the corresponding try block

### ISSUE THREAD

**Issue by zengsentry** [openkm/document-management-system#317]
the code show error after updating the  V6.3.11
Exception 'com.openkm.core.LockException' is never thrown in the corresponding try block

![20211224111815](https://user-images.githubusercontent.com/17687248/147326296-0fcbda72-5837-445f-9a0f-264d43045940.png)
![1224134315](https://user-images.githubusercontent.com/17687248/147326308-1af83a34-3f15-4845-adff-3875911fb376.png)

**Comment by gnujavasergio** [comment]
Hello, that exception was added in this issue https://github.com/openkm/document-management-system/issues/265

Exactly here https://github.com/openkm/document-management-system/pull/274/files#diff-7da546af018ee9fe83703cb84d7dfa7b697d0b3d8ec799df78faa9a7e4d6b68c

I checked the code and everything is correct.

The v6.3.11 release was also reviewed and it does not have that problem that it mentions.

```bash
git fetch origin
git tag -l
git checkout tags/v6.3.11 -b 6.3.11
```
