### ISSUE TITLE
Docker Could not convert socket to TLS

### ISSUE THREAD

**Issue by matsievskiysv** [openkm/document-management-system#321]
[openkm/openkm-ce](https://hub.docker.com/r/openkm/openkm-ce/tags) docker container has broken mail sending facility due to the TLS issues. This issue is [described on the forum](https://forum.openkm.com/viewtopic.php?p=53139&hilit=SSL#p53139) and has a known solution: updating `/opt/tomcat/lib/mail-1.5.2.jar` to `1.6.2` version.

**Comment by monkiki** [comment]
I've updated the library to v1.6.2 and Tomcat to v8.5.69.

**Comment by matsievskiysv** [comment]
Hello! The docker image was updated 3 months and it contatins the same problematic library. Could you, please, update it again?

**Comment by monkiki** [comment]
I've just updated the images. Please ensure you have deleted the local images before downloading the new one.

Best regards.
