### ISSUE TITLE
Remove DES from SecureStore

### ISSUE THREAD

**Issue by akwick** [openkm/document-management-system#322]
During an empirical study to understand the nature of cryptographic misuses in enterprise-driven projects on GitHub, we randomly inspected a few of the misuses. One of the misuses for which we could confirm as a true positive of the analysis, [CogniCryptSAST](https://github.com/CROSSINGTUD/CryptoAnalysis), is in this project. 

- [com.openkm.util.SecureStore](https://github.com/openkm/document-management-system/blob/master/src/main/java/com/openkm/util/SecureStore.java#L40): Use DES as encryption. However, DES is not considered as secure anymore. Industrial tools like [SonarSource](https://rules.sonarsource.com/java/RSPEC-5547) consider the usage of DES as critical as well.

**Comment by darkman97i** [comment]
Thanks for the advisor. Really was an old section of code not used, I will remove it.
