### ISSUE TITLE
Document Service end point does not consider the "increment" field during checkin operation, so only minor version is updated

### ISSUE THREAD

**Issue by rohitmp** [openkm/document-management-system#323]
Current behavior
Document Service REST end point does not consider the "increment" field during checkin operation, so only minor version is getting updated.

Expected behavior
Document Service REST end point does not honor the "increment" field, being send in the param "increment" to be considered and then update the respective version.

It should support following
INCREASE_DEFAULT = 0;
INCREASE_MINOR = 1;
INCREASE_MAJOR = 2;
INCREASE_MAJOR_MINOR = 3;

Seen in 
OKM Version: 6.3.12

**Comment by darkman97i** [comment]
It seems a bug in the API. I have created a pull request to solve it  ( if you wish can try it ).
