### ISSUE TITLE
Reporting Security Issue

### ISSUE THREAD

**Issue by izdiwho** [openkm/document-management-system#333]
Hi,

Reached out via contact form on your website to ask on how to report a security issue. It be coming from Izdihar (myself).

Appreciate the guidance and response on that.

Thanks.

**Comment by monkiki** [comment]
Please, describe the security issue.

Best regards.

**Comment by izdiwho** [comment]
Basically a stored XSS is found in the application, though requires user
interaction to trigger it. Should I fully disclose this here or send it
privately?

**Comment by monkiki** [comment]
Please, send me an email to mjaj6i8h@duck.com
