### ISSUE TITLE
PDF Text extraction fails on 6.3.12

### ISSUE THREAD

**Issue by aldemira** [openkm/document-management-system#348]
I just reverted back to 6.3.9 and it works flawlessly. I tried rebuilding indexes etc. But I see errors that text etraction had failed. Hence the search doesn't produce anything at all. 6.3.9 works fine.

**Comment by monkiki** [comment]
I've checked and works fine. So, provide a sample PDF to test.

**Comment by aldemira** [comment]
OK, let's do this, I can't freshly install 6.3.12 now so I'll be closing this issue, whenever I can. I'll install a fresh copy and test it. Thanks.

**Comment by aldemira** [comment]
I kinda feel ashamed but I think I forgot to delete the local volume (tomcat) which was the issue this time. So reinstalled again and now search and text extraction works. Sorry for spamming your inbox (yet again)

**Comment by monkiki** [comment]
Anyway, if you have these kind of problems again, check the list of text extractor because you may have collisions.

Best regards.

**Comment by darkman97i** [comment]
Disable the plugin named CuneiformTextExtractor ( from Administration > Tools > Plugins ) , you should have enabled one named Tesseract
