### ISSUE TITLE
Confirm the pull #34 request goes with all browsers

### ISSUE THREAD

**Issue by darkman97i** [openkm/document-management-system#35]
Check copy to clipboard goes right from all the browsers
pull request url -> https://github.com/openkm/document-management-system/pull/34

**Comment by Beau-M** [comment]
Tested on Android, IOS (emulated), Windows Phone, and Windows (10, 8.1, 8, 7).

Internet Explorer 6 - Could not test, error after log-in - Error getting translations: No row with the given identifier exists: [com.openkm.dao.bean.Language#en-au]
Internet Explorer 7 - Could not test, error after log-in - Error getting translations: No row with the given identifier exists: [com.openkm.dao.bean.Language#en-au]
Internet Explorer 8 - Could not test, error after log-in - Error getting translations: No row with the given identifier exists: [com.openkm.dao.bean.Language#en-au]
Internet Explorer 9 - Could not test, error after log-in - Error getting translations: No row with the given identifier exists: [com.openkm.dao.bean.Language#en-au]
Internet Explorer 10 - Runs with one-time permission request to access clipboard
Internet Explorer 11 - Runs with one-time permission request to access clipboard

Google Chrome 58.0.3029.83 - Works no issues or requests
Google Chrome 61.0.3163.79 - Works no issues or requests
Google Chrome 61.0.3163.91 - Works no issues or requests
Google Chrome 61.0.3163.100 - Works no issues or requests
Google Chrome 62.0.3202.62 - Works no issues or requests
Google Chrome 62.0.3202.75 - Works no issues or requests

Chromium 51.0.2684.0 - Works no issues or requests

Mozilla Firefox 55.0.1 - Works no issues or requests
Mozilla Firefox 55.0.3 - Works no issues or requests
Mozilla Firefox 56.0 - Works no issues or requests
Mozilla Firefox 56.0.1 - Works no issues or requests
Mozilla Firefox 56.0.2 - Works no issues or requests

Mozilla Firefox Beta 57.0b14 - Works no issues or requests

Mozilla Firefox Developer 55.0b1 - Works no issues or requests

-earlier versions of Opera: error with installation
Opera 33.0.1990.43 - Works no issues or requests
Opera 34.0.2036.25 - Works no issues or requests
Opera 35.0.2066.68 - Works no issues or requests

Safari (all versions) - Could not test, error after log-in - Error getting translations: No row with the given identifier exists: [com.openkm.dao.bean.Language#en-us]

**Comment by gnujavasergio** [comment]
Add Clipboard Document     
- Clipboard in URL
- Clipboard in Webdav
- Clipboard in uuid 

Add Clipboard Folder
- Clipboard in URL
- Clipboard in Webdav
- Clipboard in uuid

Add Clipboard Mail
- Clipboard in URL
- Clipboard in Webdav
- Clipboard in uuid

## Test

Firefox 56.0 (64-bit) - Works no issues
Google Chrome Versión 62 (64 bits) - Works no issues
Opera 48 - Works no issues
Internet Explorer 10 - Runs with one-time permission request to access clipboard
Internet Explorer 11 - Runs with one-time permission request to access clipboard
