### ISSUE TITLE
How does OpenKM verify the file uploaded correctly or not ?

### ISSUE THREAD

**Issue by zengsentry** [openkm/document-management-system#359]
Dear team
does it mean that all the uploaded file is correct and no corrupted files?

Best Regards

**Comment by darkman97i** [comment]
OpenKm calculates a checksum that later can be used to check if the checksum in the OpenKM repository is still the same. About the uploading process, this kind of magic does not exist, you upload an stream with a size and this stream is stored on the OpenKM side. Once on the OpenKM side, the application has control of the file, not before.

**Comment by zengsentry** [comment]
thank you for you clarify.
