### ISSUE TITLE
Who to contact for security issues

### ISSUE THREAD

**Issue by psmoros** [openkm/document-management-system#361]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@ahrixia) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by ahrixia** [comment]
Hi, I have already mailed someone after getting a reply from contact form. It's been weeks and no updates. Could you please check thanks!

**Comment by darkman97i** [comment]
can tell us the subject you used?

**Comment by ahrixia** [comment]
@darkman97i I emailed to Jllort and the subject was "Security Bug: OpenKM"

**Comment by darkman97i** [comment]
Nothing was found with this subject. Send the email again indicating "community edition security issues #361"

https://www.openkm.com/en/contact.html
