### ISSUE TITLE
Gentoo is an 'unknown distro' and cannot install openkm

### ISSUE THREAD

**Issue by NucleaPeon** [openkm/document-management-system#362]
```
vagrant@gentoo64 ~ $ sudo java -jar OKMInstaller.jar 
Running on Linux: 0.9.23-CE (build: 1cb41ce)
Linux distro: unknown (Unknown - 0)
Local host: gentoo64 (127.0.0.1)
Java version: 1.8.0_362
Free disk size: 12.1 GB
RAM size: 7.8 GB
CPU cores: 4
Server IP: 10.0.2.15
Supported databases: [h2, hsqldb, mariadb, mysql, oracle, postgresql, sqlserver]
Current directory: /home/vagrant

Database [h2]: mariadb
Database host [localhost]: 
Database name [okmdb]: 
Database user [openkm]: 
Database password [#m3Np1S@YhQb]: *************
---------------------------
- Database: mariadb
- Database host: localhost
- Database name: okmdb
- Database user: openkm
- Database password: ********************
- OpenKM version: 6.3.12
- Tomcat version: 8.5.69
---------------------------
Start install process? [y/N]: y

- Downloading Tomcat: 8.5.69
File already downloaded
- Unzipping archive. Done!
- Fix permissions... Done!
- Create symbolic link... Done!
- Downloading OpenKM: 6.3.12
Resume download ........*.... 40% ....*.... 50% ....*.... 60% ....*.... 70% ....*.... 80% ....*.... 90% ....*.... 100%
- Unzipping archive. Done!
- Check archive integrity... Done!
- Copy OpenKM
- Configure OpenKM
- Configure service
ERROR: Unknown Linux distro: unknown
```

Is it necessary to know the linux distro? If it's failing on the service step, would it be more viable to have an option flag for using systemd or openrc/init.d and skip distro detection? I haven't looked into the code yet so I don't have much context to this error. Would you support having Gentoo as a known distro if I worked on adding it?

**Comment by monkiki** [comment]
I know Gentoo but never used it, but I think is more used in desktop than servers.

The install automatically install some third-party dependencies like LibreOffice and I don't even know which package manager uses Gentoo. Anyway, the installer helps but If you want to install OpenKM in Gentoo you can also make a manual installation (download Tomcat, download OpenKM and configure it). Please, check https://docs.openkm.com/kcenter/view/okm-6.4/installing-on-ubuntu-and-debian-(manual).html

**Comment by NucleaPeon** [comment]
![Screenshot_20231026_135500](https://github.com/openkm/document-management-system/assets/1475151/5f28d71c-0e4d-4be5-b9bd-947fc65d16be)

I'm assuming that I'll be able to view the article once I create an account.
It might make more sense to create an ebuild for gentoo specifically instead of modifying your script, so that gives me a good direction to look in. 

Thanks for your help. If/when I get that done, I can reach out again. Cheers.

**Comment by monkiki** [comment]
Sorry, the right link is this one:

https://docs.openkm.com/kcenter/view/okm-6.3-com/installing-on-ubuntu-and-debian-(manual).html

Best regards.
