### ISSUE TITLE
eula-openkm-end-user-license-agreement.html 404 error

### ISSUE THREAD

**Issue by NucleaPeon** [openkm/document-management-system#363]
![Screenshot_20231031_131254](https://github.com/openkm/document-management-system/assets/1475151/cf3d08d8-bee5-4e20-97d1-9392bcf58fc0)

I was looking at the source of pom.xml and the license xml tag links to https://docs.openkm.com/kcenter/view/licenses. Clicked on ``[EULA - OpenKM End User License Agreement](https://docs.openkm.com/view/licenses/eula-openkm-end-user-license-agreement.html)`` and got a 404.

Clicking in the sidebar goes to this page: https://docs.openkm.com/kcenter/licenses/eula-openkm-end-user-license-agreement.html which ALSO 404's, but is a tomcat error page.

**Comment by NucleaPeon** [comment]
The OpenKM SDK end user license agreement also 404's.

**Comment by darkman97i** [comment]
Only users with credentials have access to it. I have updated the documentation to remark it.
