### ISSUE TITLE
openkm.com maven repository / missing artifacts?

### ISSUE THREAD

**Issue by kr428** [openkm/document-management-system#38]
Hi *;

building current sources at the moment fails because artifacts because several artifacts don't seem to be available (in the right places?) anymore. See:

`[ERROR] Failed to execute goal on project OpenKM: Could not resolve dependencies for project de.planconnect:OpenKM:war:6.3.3.1-SNAPSHOT: The following artifacts could not be resolved: com.github.dcarter.gdata-java-client:gdata-contacts-3.0:jar:1.46.0, com.github.dcarter.gdata-java-client:gdata-client-1.0:jar:1.46.0, com.github.dcarter.gdata-java-client:gdata-core-1.0:jar:1.46.0, com.github.dcarter.gdata-java-client:gdata-docs-3.0:jar:1.46.0, com.github.dcarter.gdata-java-client:gdata-media-1.0:jar:1.46.0, com.github.dcarter.gdata-java-client:gdata-spreadsheet-3.0:jar:1.46.0: Could not find artifact com.github.dcarter.gdata-java-client:gdata-contacts-3.0:jar:1.46.0 in openkm.com (http://maven.openkm.com/maven2) -> [Help 1]`

Same happened before for com.ettrema:milton-api:jar:1.8.1.3; haven't found this version publicly available anywhere but in these case we at least used to have them in some local .m2/repository. What's wrong here? 

Thanks in advance and all the best,
Kristian

**Comment by monkiki** [comment]
Can you try again? Thanks.

**Comment by kr428** [comment]
Seems to work again.
Thanks! :)

**Comment by monkiki** [comment]
Great!
