### ISSUE TITLE
InpustStream -> is.available() is limited to 2GB not allowing file >2GB to download properly

### ISSUE THREAD

**Issue by omnicron10** [openkm/document-management-system#40]
If there is a file in repository larger than 2GB, only the first 2GB of the file will be downloaded.  This appears to be related to InpustStream -> is.available() and a 2GB limit.  Apparently the integer is not able to handle file sizes over 2GB.  

To verify:
1) upload file larger than 2GB to OpenKM
2) download file larger than 2GB from OpenKM
3) Web browser will file as 2GB and only 2GB will download.

**Comment by gnujavasergio** [comment]
Test was done and now download correctly
