### ISSUE TITLE
OpenKM-6.3.4 Installer Clears "path" environment variable

### ISSUE THREAD

**Issue by PSHREYASHOLLA** [openkm/document-management-system#44]
When we install OpenKM-6.3.4 community edition, 'path' environment variable is getting cleared on windows machine.
It replaces previous %path configurations and populates it with "%PATH%;C:\tomcat-7.0.61\lib\sigar;"

**Comment by monkiki** [comment]
I've uploaded a new version at https://sourceforge.net/projects/openkm/files/common/

Regards.

**Comment by PSHREYASHOLLA** [comment]
Is the same available in https://www.openkm.com/en/download.html as well?

As, we will be suggesting others to download OpenKM from official site.

Thanks.

**Comment by monkiki** [comment]
Use this link https://sourceforge.net/projects/openkm/files/common/OKMInstaller.jar/download

**Comment by PSHREYASHOLLA** [comment]
![image](https://user-images.githubusercontent.com/19671054/33536303-21de25c0-d8da-11e7-845c-862d32d29996.png)

Thanks,

I was asking if the same is available as part of  https://www.openkm.com/en/download.html page as well. Please find the attached image. As we would be suggesting our team people to download OpenKM from the official site.

**Comment by monkiki** [comment]
In the web page there is a link to SourceForge (https://sourceforge.net/projects/openkm/files/common/OKMInstaller.jar/download), so is the same file.

**Comment by monkiki** [comment]
Shall I mark this issue as solved?

**Comment by PSHREYASHOLLA** [comment]
Yes it works. Thanks

**Comment by monkiki** [comment]
Thanks for the feedback!
