### ISSUE TITLE
Service 'openkm' is missing the ImageFile

### ISSUE THREAD

**Issue by shahareldad** [openkm/document-management-system#45]
Hi all

I am trying to install the community edition.
My OS is Windows 10 pro.
Browser is Chrome version 62.
JDK 1.8
MYSQL server 5.7
OpenKM jar 6.3.4

When I run "java -jar OKMInstaller.jar" I get "Failed installing 'OpenKM' service".
When I run "service.bat install" I get the same.
When I run "openkm.exe" I get "Service 'openkm' is missing the ImageFile" and "Failed to run service as console application".
Also in the bin folder I do not see the tomcat7.exe file and tomcat7w.exe file even though I installed this via openkm installer.

Anyone has any idea?
here is a link to the openkm forum post: 
https://forum.openkm.com/viewtopic.php?f=3&t=21569&p=44953#p44953
and to the screen shot
https://forum.openkm.com/download/file.php?id=1987&mode=view

Thanks
Shahar

**Comment by shahareldad** [comment]
After a lot of work and commenting in the forum we worked it and now its working, You can see in the forum link all done to solve this.

**Comment by monkiki** [comment]
So, should I close this ticket?

**Comment by shahareldad** [comment]
Yes, thank you
