### ISSUE TITLE
The comment of a version is not saved when checking in using PHP library

### ISSUE THREAD

**Issue by andrw00** [openkm/document-management-system#46]
The 'comment' is not being saved in the document versions when doing a checkin using the PHP library.

Im using version 6.3.4, PHP library version 1.1.2.

**Comment by andrw00** [comment]
Correction: The comment is saved. Is the function "getVersionHistory" what seems to be failing: The field "comment" always comes empty even when it is correctly stored in the OKM server.

**Comment by gnujavasergio** [comment]
Hello
I attached the new sdk4php of the community version with the correction of the bug I found.
regards
[sdk4php-1.1.3.zip](https://github.com/openkm/document-management-system/files/1722277/sdk4php-1.1.3.zip)

**Comment by darkman97i** [comment]
Solved
