### ISSUE TITLE
can not purge trash 

### ISSUE THREAD

**Issue by jawharOmar** [openkm/document-management-system#48]
I  using openkm via it's API I make folder and delete it , after some white I saw the OpenKM is  too slow i login to the default web interface i see trash was too growing i decide to purge the trash but when i tried to remove the big folder i get below error 

Cant' delete file (not exists) '/home/joh/Desktop/okm-installer/tomcat-7.0.61/repository/datastore/1f/5a/0c/b5/1f5a0cb5-d30d-479d-bf2b-33497d875adb

Note: my openkm versionis 6.3.4
also i install two instance of openkm with diffrent PORT 8080,8081  but with same database but now i deleted one of them

**Comment by darkman97i** [comment]
Seems an issue with documents what should exists but no longer exists. To solve it, first must execute a repository checker ( with history enabled ) in the trash node. From there you will see some errors -> missing documents -> what you should create by hand to solve the issue.
