### ISSUE TITLE
How to import open km source code to eclipse

### ISSUE THREAD

**Issue by souravprakashjena** [openkm/document-management-system#51]
Can anyone please help to import the source code open km to Eclipse

**Comment by darkman97i** [comment]
I suggest start reading this documentation section ( should be a good starting point ):
https://docs.openkm.com/kcenter/view/okm-6.3-com/configuring-ide-from-a-clean-eclipse.html
https://docs.openkm.com/kcenter/view/okm-6.3-com/checkout-source-code-from-git.html

Tell us if you success on it or if you have issues while trying.

**Comment by souravprakashjena** [comment]
@darkman97i.     I successfully checkout the code   from GitHub to eclipse ide but when try it to run the project using tomcat in eclipse it throwing some error.can you please help me out.

**Comment by darkman97i** [comment]
Did you success on build the war ?
You must use the tomcat from https://sourceforge.net/projects/openkm/files/common/

**Comment by souravprakashjena** [comment]
Thanks @darkman97i  .Now i am able to run the source code through my ide .But now i am facing issue after the login .Its unable to render to index .jsp page . iam attaching the screenshot below.

![image](https://user-images.githubusercontent.com/13752535/34861096-3a3a75ca-f788-11e7-95c8-aff68aa95b32.png)

**Comment by darkman97i** [comment]
The GWT has not been compiled, take a look here https://docs.openkm.com/kcenter/view/okm-6.3-com/development-tips.html#ConfigureGWTbuildfromeclipse 

I think the screenshot in the previous url is older, the goals should be:
clean gwt:compile compile 

We will release the development environment with all configured ( 11GB VM ) what comes with linux and everything installed into yet to be used. It's needed about 2 core and 4GB for get it running,if you want to test it I can share with you the url ( it's an OVA what can be imported from Virtual Box or VmWare )

**Comment by darkman97i** [comment]
Seems you have some issue accessing https://repo.maven.apache.org/maven2/ , I have checked the url and is working for me.

**Comment by souravprakashjena** [comment]
@darkman97i. I have  compiled the GWT with this GOAL VALUE="clean gwt:compile compile".But still it unable to render into index.jsp page

**Comment by darkman97i** [comment]
Check into the war you have created exists frontend folder. Remove work/Catalina/localhost folder to be sure cache is cleaned and also webapps/OpenKM folder ( deployed ). If you take a look at build.sh or build.bat you will see:
mvn -Dmaven.test.skip=true clean gwt:compile install

**Comment by darkman97i** [comment]
Is the issue solved ?
