### ISSUE TITLE
PDF still can be downloaded on preview after disable PDF download on user profile

### ISSUE THREAD

**Issue by zamp21** [openkm/document-management-system#54]
OKM version:6.3.4;
Description: 
1, disable PDF download privilege on user profile for user A
2, login as this user A
3, navigate to the PDF file which user A has read privilege (w/o write)
4, preview this PDF document
5, user A can download the PDF file on pdf viewer on Chrome/firefox or download it via a right-click menu on Edge.

It would need to hide the toolbar and rightclick of pdf viewer.

**Comment by monkiki** [comment]
This only works with path paid version of the previewer. The one included in OpenKM Community does not have this feature.

**Comment by vohoailen** [comment]
You can disable this feature by yourself, here is the guidelines to do:
1. Go to the class: com.openkm.frontend.client.widget.toolbar.ToolBar, you will see all the options menu should be here.
2. On the checkToolButtonPermissions method, we can set show/hide the options menu with User's permission on this method.

**Comment by zamp21** [comment]
@monkiki Thanks for the info.
@vohoailen Thanks for the suggestion. I guess it's a pdf.js configuration issue. Let me have a try.

**Comment by monkiki** [comment]
Can I close this issues or it requires any further action to be solved?
