### ISSUE TITLE
Automation to capture move of node TO new folder path

### ISSUE THREAD

**Issue by hdferguson3** [openkm/document-management-system#55]
I have been trying to create an automation rule to capture the movement of a node (file) to a specified folder.

When using the automation 

![screenshot from 2018-02-22 13-56-43](https://user-images.githubusercontent.com/34278872/36558284-87873da2-17d8-11e8-937e-8384d8b899c4.png)

![screenshot from 2018-02-22 13-57-01](https://user-images.githubusercontent.com/34278872/36558303-971da828-17d8-11e8-9426-a77457062778.png)

Nothing happens after the document move and I see the following in openkm.log

```
2018-02-22 13:57:28,825 [http-bio-10.30.40.185-8180-exec-349] [] ERROR c.o.a.validation.PathContains - null
java.lang.NullPointerException: null
	at com.openkm.automation.validation.PathContains.isValid(PathContains.java:49) ~[PathContains.class:na]

```

**Comment by gnujavasergio** [comment]
Hello @hdferguson3 

It was found because it fails to resolve it we will let you know when it is solved.

regards

**Comment by hdferguson3** [comment]
Thank you for looking into this.

**Comment by hdferguson3** [comment]
I apologize, but can you point me towards instructions on how to do this? If I assume this is some source branch here on Github, I have yet to pull, compile and deploy.

**Comment by darkman97i** [comment]
We are in process of releasing the version 6.3.5 if you wait for a while in this week you will be able to downloading it.
