### ISSUE TITLE
Graphics Designer/ Logo Designer

### ISSUE THREAD

**Issue by dibon-github** [openkm/document-management-system#66]
Good day, I would be willing to collaborate and make a new logo design for your app. Pls do reply if you accept my offer. I do work for free, dont worry. I would do anything for the benefit of this project.

**Comment by monkiki** [comment]
Do you have any proposal?

**Comment by dibon-github** [comment]
Good day, thanks for replying, i will be giving you some proposal logos tomorrow for you to choose from.

**Comment by dibon-github** [comment]
This would be a modern approach for your old logo, you will not be needing anymore to put a white background for I had made this design to standout on its background by selecting colors that compliment to it.

**Comment by dibon-github** [comment]
You could click on the image sir to see the full resolution of the photos

**Comment by monkiki** [comment]
Your design is great.

**Comment by dibon-github** [comment]
Thank you. You could use it, and you can download the logo here:
https://drive.google.com/open?id=1w4IBkBqZ_w5LR7vcDDPZEJlZGoMZbjFx
Im happy to have helped and contribute for this project.

**Comment by monkiki** [comment]
Contributions are always welcomed :)

**Comment by dibon-github** [comment]
Looking forward to seeing it sir. :) 
Id also added logos for the small thumbnail image of the webpage.
You can check and download it here:
https://drive.google.com/open?id=1RyslrZ7io-ro22TJD18eINiL013KhkQv

size variations sir from 1024px down to 32px
