### ISSUE TITLE
Autoscript renaming throws error message "Document path not found"

### ISSUE THREAD

**Issue by jorseng** [openkm/document-management-system#70]
Hi,
As requested to post an issue here, referring to the post in the link below.

[https://forum.openkm.com/viewtopic.php?f=31&t=21830](url)

When metadata scripting is applied to change file name from XXXX.pdf to YYYY.pdf, the UI is trying to look for XXXX.pdf. Where the UI did not evaluate if the name has been changed before trying to refresh to previous path thus causing the error below.

![error message](https://user-images.githubusercontent.com/34156375/40951706-b9e29670-68aa-11e8-8743-69d4a3b72fb8.PNG)

![automation prompt](https://user-images.githubusercontent.com/34156375/40951715-c05faccc-68aa-11e8-84a9-32c6fcc19e5c.PNG)

![automation action](https://user-images.githubusercontent.com/34156375/40951719-c21d2ada-68aa-11e8-84d9-06f91aa87140.png)

Thank you!

**Comment by darkman97i** [comment]
@gnujavasergio follow the code in professional editon when you modify metadata and you will see we evaluate if the node path has been changed ( there we use the UUID what should be used here too ).
