### ISSUE TITLE
Filter nodes not working in Category

### ISSUE THREAD

**Issue by hdferguson3** [openkm/document-management-system#71]
I have noticed that the filter options aren't available when looking at nodes in the Categories view.
![screenshot from 2018-05-16 13-05-30](https://user-images.githubusercontent.com/34278872/41292099-8b57d386-6e1f-11e8-865c-82a16897ceb7.png)

Version 6.4.3 (build 47204ef)

**Comment by darkman97i** [comment]
@gnujavasergio  consultalo conmigo antes de nada ( no tengo claro que esta funcionalidad en esta vista pueda funcionar ).
