### ISSUE TITLE
Data pattern in Polish language translation wasn't set correctly

### ISSUE THREAD

**Issue by dpajakpolsl** [openkm/document-management-system#72]
Hello

I found mistake in Polish language translation for OpenKM Community. Date pattern wasn't set correctly. 

Please change this lines from:

INSERT INTO OKM_TRANSLATION (TR_MODULE, TR_KEY, TR_TEXT, TR_LANGUAGE) VALUES ('frontend', 'general.date.pattern', 'dd.MM.yyyy hh:mm:ss', 'pl-PL');
...
INSERT INTO OKM_TRANSLATION (TR_MODULE, TR_KEY, TR_TEXT, TR_LANGUAGE) VALUES ('extension', 'general.date.pattern', 'dd.MM.yyyy hh:mm:ss', 'pl-PL');

to 

INSERT INTO OKM_TRANSLATION (TR_MODULE, TR_KEY, TR_TEXT, TR_LANGUAGE) VALUES ('frontend', 'general.date.pattern', 'dd.MM.yyyy HH:mm:ss', 'pl-PL');
...
INSERT INTO OKM_TRANSLATION (TR_MODULE, TR_KEY, TR_TEXT, TR_LANGUAGE) VALUES ('extension', 'general.date.pattern', 'dd.MM.yyyy HH:mm:ss', 'pl-PL');

Best regards,
Daniel Pająk.

**Comment by gnujavasergio** [comment]
@darkman97i issue resolved

@dpajakpolsl The file OpenKM_6.3_pl-PL.sql has already been updated in the documentation, you can download it in:

OpenKM_6.3_pl-PL.sql

https://docs.openkm.com/kcenter/view/okm-6.3-com/language-translations.html

regards

**Comment by dpajakpolsl** [comment]
@gnujavasergio Thank you very much

Best regards
