### ISSUE TITLE
Copy URL to a file won't work by UUID

### ISSUE THREAD

**Issue by peterbraemac** [openkm/document-management-system#77]
Using the URL to reference a document in OpenKM doesn't work by UUID if the default language is set to something. The issue is present in version CE 6.3.6. See full discussion and suggested fix in the forums here:
    [https://forum.openkm.com/viewtopic.php?f=5&t=9826&start=15](https://forum.openkm.com/viewtopic.php?f=5&t=9826&start=15)

In order to fix the issue, the file index.jsp needs to be changed. The below line, which is currently line 29:
`if (docPath != null || fldPath != null) {`

Needs to be changed to:
`if (docPath != null || fldPath != null || uuid != null) {`

**Comment by peterbraemac** [comment]
Here is the path to the index.jsp file that needs to be updated:
`src/main/webapp/index.jsp`

**Comment by peterbraemac** [comment]
I am a newbie with GitHub so messed up the change/pull request. Anyway, I tried to create a pull request here:
# #78 

Note that the second change (at the end of the file) was not on purpose and should not be included (empty line at end of file). Only the if statement should be changed.

**Comment by gnujavasergio** [comment]
Mergue 
https://github.com/openkm/document-management-system/pull/78
