### ISSUE TITLE
Massive add category not working in 6.3.6-87d181f release

### ISSUE THREAD

**Issue by xiaofami** [openkm/document-management-system#79]
The button of "add category" would turn grey when I selected more than one file. However it is supposed to be functional as the desription in wiki site https://www.openkm.com/wiki/index.php/Massive_add_category. It is a great pain when dealing with thousands of files ...

**Comment by darkman97i** [comment]
Add an screenshot for better understanding about what are you doing.

**Comment by xiaofami** [comment]
![003](https://user-images.githubusercontent.com/4654044/42265210-773f8fc8-7fa5-11e8-9df7-17ffda8b7331.png)

**Comment by darkman97i** [comment]
Seems possible bug@gnujavasergio , if the feature is not present into community version add it.
