### ISSUE TITLE
Downloading the file with a wrong file name with openkm-joomla extension

### ISSUE THREAD

**Issue by bionexit** [openkm/document-management-system#80]
when downloading files with openkm-joomla extension, the file with a wrong name.
I'm using IE 8.0
Please kindly help.

Ref https://forum.openkm.com/viewtopic.php?f=3&t=21866&p=46081#p46081

**Comment by gnujavasergio** [comment]
Hi.
You can try it on edge 11 or a more updated internet explorer.
Internet Explorer 8 is already deprecated.

and then inform us if you have the same problem.
regards
