### ISSUE TITLE
Upgrade GWT version

### ISSUE THREAD

**Issue by darkman97i** [openkm/document-management-system#83]
upgrade current gwt version to enable super dev mode

**Comment by darkman97i** [comment]
@gnujavasergio bájate la rama y comprueba que los test unitarios del SDK de java funcionan correctamente, tambien me gustaría que hagas un par de pruebas básicamas ( crear carpetas, documentos, y probar tambien el buscador ), en principio tiene que funcionar todo sin problemas después de este cambio de la versión GWT. Cuando este hecho, me devuelve el ticket a mi nuevamente.

**Comment by gnujavasergio** [comment]
@darkman97i ya esta actualizado la api rest se iso las pruebas de todos los metodos con el SDK4j-1.2
Realize pruebas en la interfaz subiendo todo tipo de archivos el unico fallo que encontre fue en las busquedas no se puede realizar busquedas utilizando (*) y (?) como por ejemplo si quiero buscar por

*ertificad?

**Comment by gnujavasergio** [comment]
@darkman97i @monkiki las busquedas por contenido ya esta funcionando con mysql pero para que funcione correctamente se borro un parametro en la configuración en el server.xml

<Resource auth="Container" driverClassName="com.mysql.jdbc.Driver" maxIdle="30" maxTotal="100" maxWaitMillis="10000" name="jdbc/OpenKMDS" password="openkm" type="javax.sql.DataSource" url="jdbc:mysql://localhost:3306/okm_db_636?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=UTF8" username="openkm" validationQuery="select 1"/>

Se tiene que quitar este parametro para que funcione correctamente un mysql

&amp;characterEncoding=UTF8

https://stackoverflow.com/questions/13653712/java-sql-sqlexception-incorrect-string-value-xf0-x9f-x91-xbd-xf0-x9f
http://pinter.org/archives/5884
