### ISSUE TITLE
Build docker image

### ISSUE THREAD

**Issue by rickywu** [openkm/document-management-system#92]
I found docker image on docker hub but no Dockerfile, how can I build my image?

**Comment by rickywu** [comment]
FROM openjdk:8

ENV TOMCAT_VERSION 8.5.24
ENV OPENKM_VERSION 6.3.6
ENV CATALINA_HOME /usr/local/tomcat-${TOMCAT_VERSION}
ENV OPENKM_HOME /opt/openkm
ENV PATH $PATH:$JAVA_HOME/bin:${CATALINA_HOME}/bin

RUN apt-get -y update  && \
    apt-get -y install libreoffice imagemagick swftools liblog4j1.2-java libgnumail-java ant curl unzip sudo tar libreoffice-common && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /tmp/*

RUN curl -L https://nchc.dl.sourceforge.net/project/openkm/common/Tomcat-${TOMCAT_VERSION}.zip -o /usr/local/tomcat.zip && \
    unzip /usr/local/tomcat.zip -d /usr/local/ && \
    curl -L https://nchc.dl.sourceforge.net/project/openkm/${OPENKM_VERSION}/OpenKM-${OPENKM_VERSION}.zip -o /usr/local/openkm.zip && \
    unzip /usr/local/openkm.zip -d /usr/local/ && \
    mv /usr/local/OpenKM.war /usr/local/tomcat-${TOMCAT_VERSION}/webapps/ && \
    rm /usr/local/openkm.zip && \
    rm /usr/local/tomcat.zip && \
    ln -s ${CATALINA_HOME} ${OPENKM_HOME}

VOLUME ${OPENKM_HOME}/repository

CMD $CATALINA_HOME/bin/catalina.sh run

EXPOSE 8080 2002

**Comment by omidraha** [comment]
Hi,
Where is Dockerfile of https://hub.docker.com/r/openkm/openkm/ ?

**Comment by bluemix** [comment]
@omidraha 
https://hub.docker.com/r/openkm/openkm-ce
